import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import { useEffect, useState } from "react"

const inter = Inter({ subsets: ["latin"] });

const clamp = (value: number, min: number, max: number): number => {
  return Math.min(Math.max(value, min), max);
}

export default function Home() {

  const [rotation, setRotation] = useState(0)

  useEffect(() => {
    const handleMouseMove = (event: any) => {
      const { clientX, clientY } = event
      setRotation(clamp((clientX - window.innerWidth / 2) / 10, -90, 90))
    }

    window.addEventListener("mousemove", handleMouseMove)

    return () => {
      window.removeEventListener("mousemove", handleMouseMove)
    }
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <style dangerouslySetInnerHTML={{
          __html: `
            .viewportRotation {
              transform: rotate(${rotation}deg);
            }

            .viewportRotation div {
              transform: rotate(${0 - rotation}deg);
              margin: ${Math.abs(rotation)}px 0;
            }
        `}} />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        <div>Rotation: {rotation}</div>

        <div className={styles.viewport + ' viewportRotation'}>
          <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />
          </div>

          <div className={styles.grid}>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 1 <span>-&gt;</span>
              </h2>
              <p>
                Hello!
              </p>
            </a>

            <a
              href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 2 <span>-&gt;</span>
              </h2>
              <p>
                Ciao!
              </p>
            </a>

            <a
              href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 3 <span>-&gt;</span>
              </h2>
              <p>
                Hallo!
              </p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 4 <span>-&gt;</span>
              </h2>
              <p>
                Privet!
              </p>
            </a>
          </div>

          <div className={styles.grid}>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 5 <span>-&gt;</span>
              </h2>
              <p>
                Ola!
              </p>
            </a>

            <a
              href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 6 <span>-&gt;</span>
              </h2>
              <p>
                Yo!
              </p>
            </a>

            <a
              href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 7 <span>-&gt;</span>
              </h2>
              <p>
                Bon jour!
              </p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 8 <span>-&gt;</span>
              </h2>
              <p>
                Sup?
              </p>
            </a>
          </div>

          <div className={styles.grid}>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 5 <span>-&gt;</span>
              </h2>
              <p>
                Ola!
              </p>
            </a>

            <a
              href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 6 <span>-&gt;</span>
              </h2>
              <p>
                Yo!
              </p>
            </a>

            <a
              href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 7 <span>-&gt;</span>
              </h2>
              <p>
                Bon jour!
              </p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Block 8 <span>-&gt;</span>
              </h2>
              <p>
                Sup?
              </p>
            </a>
          </div>
        </div>

      </main>
    </>
  );
}
